- Cargo.toml
- src/mysql/discovery/executor/mock.rs
- src/mysql/discovery/executor/real.rs
- src/mysql/discovery/mod.rs
- src/postgres/discovery/executor/mock.rs
- src/postgres/discovery/executor/real.rs
- src/postgres/discovery/mod.rs
- src/util.rs
- Log debug message via `Log` crate instead of printing it out to stdout directly
> Log debug message

- Cargo.toml
Currently the `migration` module is missing from docs.rs
https://docs.rs/sea-schema/0.5.0/sea_schema/index.html
> Build docs.rs with `migration` features

- src/sqlite/types.rs
Closes https://github.com/SeaQL/sea-orm/issues/490
Not entirely sure why it was done with an alias, but by changing the `ColumnType` to binary the following schema (when used with `sea-orm-cli`):
```sql
CREATE TABLE "Books"
(
id             INTEGER                                  NOT NULL PRIMARY KEY AUTOINCREMENT,
title          TEXT                                     NOT NULL,
hash           BLOB                                     NOT NULL UNIQUE,
)
```
Used to produce:
```rust
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "Books")]
pub struct Model {
#[sea_orm(primary_key)]
pub id: i32,
pub title: String,
#[sea_orm(column_type = "Custom(\"BLOB\".to_owned())")]
pub hash: String,
}
```
And will now produce:
```rust
#[derive(Clone, Debug, PartialEq, …
```
> Fix Sqlite BLOB type.

- src/migration/manager.rs
- src/migration/migrator.rs
- tests/migration/src/lib.rs
- tests/migration/src/m20220118_000003_seed_cake_table.rs
- Closes SeaQL/sea-orm#522
- Related PR
- SeaQL/sea-orm#523
- `SchemaManager::get_connection` method returns `&'c DbConn`
- `SchemaManager::conn` field is of type `&'c DbConn`
> Migrate with `sea_orm::DbConn`

- src/postgres/def/types.rs
- src/postgres/writer/column.rs
`sea-orm-cli generate entity` currently treats Postgres `jsonb` columns as an unknown custom datatype, and gives its model field type `String`. It already supports `json` columns, and sea-query already supports `json_binary` in `ColumnDef`, so this just fills in the missing pieces to recognize `jsonb`.
No breaking changes.
No other changes.
> Support Postgres jsonb in entity generation

- src/postgres/query/constraints/mod.rs
- src/postgres/query/schema.rs
- Closes SeaQL/sea-orm#699
- https://www.postgresql.org/docs/current/infoschema-constraint-column-usage.html
> PostgreSQL query non-key foreign key info

- src/postgres/writer/column.rs
- tests/live/postgres/src/main.rs
- Closes SeaQL/sea-orm#586
> The SQL standard requires that writing just timestamp be equivalent to timestamp without time zone, and PostgreSQL honors that behavior.
> _https://www.postgresql.org/docs/current/datatype-datetime.html_
> PostgreSQL datetime and timestamp datatype are equivalent

- Cargo.toml
- src/mysql/writer/column.rs
- Closes SeaQL/sea-orm#704
- Dependencies:
- SeaQL/sea-query#331
> MySQL `VarBinary` column type mapping

- CHANGELOG.md
- src/mysql/writer/column.rs
- Closes SeaQL/sea-orm#684
- Dependencies:
- SeaQL/sea-query#314
- Dependents:
- SeaQL/sea-orm#685
- MySQL tables with `blob` column maps to corresponding `blob` column types in SeaQuery
> MySQL `blob` datatype maps to SeaQuery corresponding `blob` column type

- tests/discovery/mysql/Cargo.toml
- tests/discovery/postgres/Cargo.toml
- tests/discovery/sqlite/Cargo.toml
- tests/writer/mysql/Cargo.toml
- tests/writer/postgres/Cargo.toml
- tests/writer/sqlite/Cargo.toml
> Bump sqlx version in test cases

- src/mysql/query/version.rs
> Fixup - custom function without expressions has to include parentheses

- src/sqlite/def/types.rs
- Closes https://github.com/SeaQL/sea-orm/issues/637
> SQLite real datatype maps to double

- src/mysql/query/table.rs
- Closes https://github.com/SeaQL/sea-orm/issues/848
- Dependents:
- https://github.com/SeaQL/sea-orm/pull/876
> [MariaDB] discover SYSTEM VERSIONED tables

- src/postgres/def/types.rs
- src/postgres/query/column.rs
- src/postgres/writer/column.rs
- tests/live/postgres/src/main.rs
- tests/writer/postgres/src/main.rs
- Dependents:
- https://github.com/SeaQL/sea-orm/pull/1132
> Parse & write Postgres array datatypes

- src/postgres/def/types.rs
- src/postgres/parser/column.rs
- src/postgres/query/column.rs
- src/postgres/writer/column.rs
- Dependents:
- https://github.com/SeaQL/sea-orm/pull/1153
> Fix parsing of Postgres user-defined types

- .github/workflows/rust.yml
- https://github.com/actions-rs/toolchain/pull/220
- https://github.com/actions-rs/cargo/pull/217
> [CI] use `dtolnay/rust-toolchain`

- Cargo.toml
- src/mysql/probe.rs
- src/mysql/query/foreign_key.rs
- src/mysql/query/table.rs
- src/mysql/query/version.rs
- src/mysql/writer/column.rs
- src/postgres/probe.rs
- src/postgres/query/constraints/mod.rs
- src/postgres/query/enumeration.rs
- src/postgres/writer/column.rs
- src/probe.rs
- tests/live/postgres/src/main.rs
- Closes https://github.com/SeaQL/sea-schema/issues/87
> SeaQuery 0.28.x

- Cargo.toml
- sea-schema-derive/Cargo.toml
- tests/discovery/mysql/Cargo.toml
- tests/discovery/postgres/Cargo.toml
- tests/discovery/sqlite/Cargo.toml
- tests/live/mysql/Cargo.toml
- tests/live/postgres/Cargo.toml
- tests/live/sqlite/Cargo.toml
- tests/migration/Cargo.toml
- tests/writer/mysql/Cargo.toml
- tests/writer/postgres/Cargo.toml
- tests/writer/sqlite/Cargo.toml
> Caret requirements are an alternative syntax for the default strategy, `^1.2.3` is exactly equivalent to `1.2.3`.
> 
> https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements
To make the dependency specification clear and concise, I'd like to define it all in the form of `x.y.z`.
> Cleaning up dependency

- src/postgres/parser/table_constraints.rs
> okay now a new error: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/max/.cargo/registry/src/github.com-1ecc6299db9ec823/sea-schema-0.10.3/src/postgres/parser/table_constraints.rs:36:27
- Originated from https://discord.com/channels/873880840487206962/900758376164757555/1057084759223849050
> Skip parsing empty Postgres check constraints

- src/postgres/def/types.rs
- src/postgres/discovery/mod.rs
- src/postgres/parser/column.rs
- src/postgres/parser/table.rs
- tests/live/postgres/src/main.rs
- Closes https://github.com/SeaQL/sea-schema/issues/89
> Parse Postgres citext as Type::Unknown

- sea-schema-derive/Cargo.toml
- sea-schema-derive/src/lib.rs
Related with https://github.com/SeaQL/sea-orm/pull/1520 and https://github.com/SeaQL/strum/pull/1
> Update heck dependecy

- src/postgres/query/constraints/mod.rs
- src/postgres/query/schema.rs
- src/postgres/query/table.rs
- Closes https://github.com/SeaQL/sea-orm/issues/1582
> fix: skip parsing partitioned Postgres tables

- Cargo.toml
- src/postgres/def/types.rs
- src/postgres/parser/column.rs
- src/postgres/writer/column.rs
> Upgrade to SeaQuery 0.29.0-rc.2

- src/mysql/discovery/executor/mock.rs
- src/mysql/discovery/executor/real.rs
- src/mysql/discovery/mod.rs
- src/postgres/discovery/executor/mock.rs
- src/postgres/discovery/executor/real.rs
- src/postgres/discovery/mod.rs
- src/sqlite/def/table.rs
- src/sqlite/discovery.rs
- src/sqlite/error.rs
- src/sqlite/executor/mock.rs
- src/sqlite/executor/real.rs
- src/sqlx_types/mock.rs
- src/sqlx_types/real.rs
- tests/live/mysql/src/main.rs
- tests/live/postgres/src/main.rs
- tests/writer/mysql/src/main.rs
- tests/writer/postgres/src/main.rs
Previously, the code for `Executor::fetch_all` and similar functions used `.unwrap()` internally and panicked if any error happened during the call.  This could result in schema detection causing panics in cases of things like spurious network issues, connection pool exhaustion, and other transitory issues with the DB.
Fixes #106
This introduces a breaking change to the crate's public API surface.  Callers will need to be updated to handle the fact that schema detection returns `Result`s now.
This is definitely unavoidable, but updating shouldn't be too difficult.  Callers can just `.unwrap()` to retain the existing behavior of panicking in the case of any DB or connection error.
* Migrate all of the executor functions to return `Result<T, sqlx::Error>` to bubble up errors
* Update all …
> Return `Result`s from DB executor functions

- src/mysql/def/column.rs
- src/mysql/discovery/mod.rs
- src/mysql/parser/column.rs
- src/mysql/writer/column.rs
- src/mysql/writer/table.rs
- tests/live/mysql/src/main.rs
- Closes https://github.com/SeaQL/sea-schema/issues/23
> Parse MySQL column default value

- CHANGELOG.md
- Cargo.toml
- src/mysql/discovery/executor/real.rs
- src/postgres/discovery/executor/real.rs
- src/postgres/discovery/mod.rs
- src/sqlite/executor/real.rs
- tests/discovery/mysql/Cargo.toml
- tests/discovery/postgres/Cargo.toml
- tests/discovery/sqlite/Cargo.toml
- tests/live/mysql/Cargo.toml
- tests/live/mysql/src/main.rs
- tests/live/postgres/Cargo.toml
- tests/live/postgres/src/main.rs
- tests/live/sqlite/Cargo.toml
- tests/live/sqlite/src/main.rs
- tests/writer/mysql/Cargo.toml
- tests/writer/postgres/Cargo.toml
- tests/writer/sqlite/Cargo.toml
- Dependencies:
- https://github.com/SeaQL/sea-query/pull/652
- Dependents:
- https://github.com/SeaQL/sea-orm/pull/1742
> Upgrade to SQLx v0.7

- src/postgres/query/constraints/mod.rs
- tests/live/postgres/src/main.rs
* Fixes #100
* Should also fix SeaQL/sea-orm#1690
- Closes #100
- See #100 
None
> Fix incorrect discovery of composite foreign keys in PostgreSQL

- Cargo.toml
- src/sqlite/def/column.rs
- src/sqlite/def/table.rs
- src/sqlite/def/types.rs
- tests/live/sqlite/src/main.rs
Depends on https://github.com/SeaQL/sea-query/pull/735
> Rework SQLite type mapping

- Cargo.toml
- src/mysql/writer/column.rs
- src/postgres/writer/column.rs
- src/sqlite/def/column.rs
- src/sqlite/def/table.rs
- src/sqlite/def/types.rs
- tests/live/sqlite/src/main.rs
- Dependencies:
- https://github.com/SeaQL/sea-query/pull/743
> Bump SeaQuery and update blob data types

- Cargo.toml
- src/mysql/writer/column.rs
- src/postgres/def/types.rs
- src/postgres/parser/column.rs
- src/postgres/writer/column.rs
- src/sqlite/def/column.rs
- src/sqlite/def/table.rs
- src/sqlite/def/types.rs
- tests/live/mysql/src/main.rs
- tests/live/postgres/src/main.rs
- tests/live/sqlite/src/main.rs
- Continues:
- https://github.com/SeaQL/sea-schema/pull/117
- https://github.com/SeaQL/sea-schema/pull/122
> Cont. PR #117 & #122

- src/postgres/query/constraints/mod.rs
- tests/live/postgres/src/main.rs
- Closes https://github.com/SeaQL/sea-schema/issues/130
> Postgres: allow foreign key column without unique constraint

- src/postgres/discovery/mod.rs
- src/postgres/parser/mod.rs
- src/postgres/parser/pg_indexes.rs
- src/postgres/query/pg_indexes.rs
- src/sqlite/def/schema.rs
- tests/live/mysql/src/main.rs
- tests/live/postgres/src/main.rs
- tests/live/sqlite/src/main.rs
- Dependents:
- https://github.com/SeaQL/sea-orm/pull/2254
> Discover unique indexes

- sea-schema-derive/Cargo.toml
- sea-schema-derive/src/lib.rs
- Closes #128
- Upgrades Syn from v1 to v2; No change in outputs should be present, though existing tests were somewhat sparse.
- Utilizes direct emplacement of expressions instead of collapsing into literals where applicable, as `syn` v2 no longer surfaces literals directly for attributes.
> Upgrade `syn` to `2`

- src/postgres/query/enumeration.rs
- Closes [#2285](https://github.com/SeaQL/sea-orm/issues/2285)
- [#2285 Generated Rust enum ordering does not match underlying database enum ordering]
> Fix enum values ordering
